apiVersion : apps/v1
kind: Deployment
metadata:
  name: "meteor-backend"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "meteor"
  template:
    metadata:
      labels:
        app: "meteor"
    spec:
      containers:
        - name: "meteor-backend"
          image: "meteor.azurecr.io/meteorweb"
          ports:
          - containerPort: 8080
          env:
            - name: SPRING_MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: url
            - name: SPRING_MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: username
            - name: SPRING_MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongo-creds
                  key: password